### ISSUE TITLE
case sensitive font names

### ISSUE THREAD

**Issue by fabriziov** [arranger1044/enzitetobeamertheme#1]
When compiling (with xelatex) pay attention to case sensitive font names. In my case I had to edit "Open Sans Semibold" and "Open Sans Extrabold" and put "Open Sans SemiBold" and "Open Sans ExtraBold" (with capital B) in beamerfontthemeopenfonts.sty file, according to installed font names.

**Comment by arranger1044** [comment]
Yes, on every case sensitive file system one shall check the for the correct spelling of the filenames he refers to.
I do not know if this problem can be somehow solved in latex.
